const IGNORED_IPS = new Set(['127.0.0.1', '255.255.255.255', '0.0.0.0']);
const MAX_PAGE_SIZE = 30;

/**
 * ! NOTE: This mapping of Category IDs to Category names was taken 
 *   from the `threatYeti` api via the `https://threatyeti.com/assets/dist/page.min.js` endpoint
 *   and has the potential to change over time.
 *  */ 
const CATAGORYID_BY_CATAGORYNAME = 
{
    0: "Unrated",
    1: "Abortion",
    2: "Ads/Analytics",
    3: "Adult/Mature",
    4: "Alcohol",
    5: "Arts/Culture",
    6: "Auctions/Classifieds",
    7: "Audio",
    8: "Brokerage/Trading",
    9: "Business/Economy",
    10: "Chat/IM/SMS",
    11: "Child Pornography/Abuse",
    12: "Content Servers",
    13: "Dating/Personals",
    14: "Digital Postcards",
    15: "Drugs/Controlled Substances",
    16: "Education",
    17: "Email",
    18: "Entertainment",
    19: "Extreme/Gruesome",
    20: "File Sharing/Storage",
    21: "Finance",
    22: "For Kids",
    23: "Forums",
    24: "Gambling",
    25: "Games",
    26: "Government/Legal",
    27: "Hacking",
    28: "Hate/Discrimination",
    29: "Health",
    30: "Hobbies/Recreation",
    31: "Hosting",
    32: "Humor/Comics",
    33: "Alternative Ideology",
    34: "Information Technology",
    35: "Information/Computer Security",
    36: "Infrastructure/IOT",
    37: "Job Search",
    38: "Lingerie/Swimsuit",
    39: "Malicious",
    40: "Marijuana",
    41: "Marketing/Merchandising",
    42: "Media Sharing",
    43: "Military",
    44: "Mixed Content/Potentially Adult",
    45: "News",
    46: "Non-Profit/Advocacy",
    47: "Nudity",
    48: "Parked Site",
    49: "Peer-to-Peer (P2P)",
    50: "Personal Sites/Blogs",
    51: "Phishing",
    52: "Piracy/Plagiarism",
    53: "Politics/Opinion",
    54: "Pornography",
    55: "Potentially Unwanted Programs",
    56: "Productivity Applications",
    57: "Anonymizers",
    58: "Real Estate",
    59: "Reference",
    60: "Religion",
    61: "Remote Access",
    62: "Restaurants/Food",
    63: "Scam/Illegal/Unethical",
    64: "Search Engines/Portals",
    65: "Sex Education",
    66: "Shopping",
    67: "Social Networking",
    68: "Society/Lifestyle",
    69: "Software Downloads",
    70: "Spam",
    71: "Sports",
    72: "Suspicious",
    73: "Telephony",
    74: "Tobacco",
    75: "Translation",
    76: "Travel",
    77: "URL Redirect",
    78: "Vehicles",
    79: "Video/Multimedia",
    80: "Violence",
    81: "Virtual Meetings",
    82: "Weapons"
}

module.exports = { IGNORED_IPS, MAX_PAGE_SIZE, CATAGORYID_BY_CATAGORYNAME };
